Repository heig-PRO-b04/java-backend, pull requests merged in 2020-04, with the labels that each got.

#48 Improvements to the polls API
  pom.xml
  src/main/java/ch/heigvd/pro/b04/moderators/ModeratorRepository.java
  src/main/java/ch/heigvd/pro/b04/polls/PollController.java
  src/main/java/ch/heigvd/pro/b04/polls/PollRepository.java
  src/test/java/ch/heigvd/pro/b04/polls/PollControllerTest.java
Labels: requires-review

#45 Separate auth tests in two files, and rename Register
  src/main/java/ch/heigvd/pro/b04/auth/RegistrationController.java
  src/test/java/ch/heigvd/pro/b04/auth/LoginControllerTest.java
  src/test/java/ch/heigvd/pro/b04/auth/RegistrationControllerTest.java
Labels: requires-review

#46 Delete the moderators endpoint, to conform to the API
  src/main/java/ch/heigvd/pro/b04/moderators/ModeratorController.java
Labels: requires-review

#52 Add an automated workflow to update Wiki from main repo
  .github/workflows/wiki.yml
  wiki/APIv1.Moderators.md
  wiki/APIv1.Users.md
  wiki/APIv1.md
  wiki/Assets/Database.Configuration.EnvironmentVariables.png
  wiki/Assets/Database.Configuration.png
  wiki/Collaboration.md
  wiki/Database.Setup.md
  wiki/Home.md
Labels: api, documentation, enhancement

#57 Update the emoji list
  wiki/APIv1.Users.md
Labels: documentation, requires-review

#74 Add API documentation for registration endpoint, Fix #44
  wiki/APIv1.Endpoints.md
Labels: api, documentation

#61 Add a test case for empty usernames
  src/test/java/ch/heigvd/pro/b04/auth/RegistrationControllerTest.java
Labels: bug, test-case

#85 Start work on a summary of meeting plans
  wiki/Home.md
  wiki/Meetings.md
Labels: priority-medium, quality-approval

#95 Add a journal to the wiki
  wiki/Home.md
  wiki/Journal/Journal.md
  wiki/Journal/Presentation.md
Labels: waiting-for-review

#114 Fix #63
  wiki/APIv1.Endpoints.md
Labels: api, documentation

#121 Specify CORS configuration to support HTTP delete method
  src/main/java/ch/heigvd/pro/b04/CorsConfiguration.java
Labels: api, bug, waiting-for-review

#137 Fix #123
  wiki/APIv1.Endpoints.md
Labels: api, documentation

#154 Fix the /all endpoint for questions
  src/main/java/ch/heigvd/pro/b04/polls/ServerPoll.java
  src/main/java/ch/heigvd/pro/b04/questions/QuestionController.java
  src/main/java/ch/heigvd/pro/b04/questions/ServerQuestion.java
  src/main/java/ch/heigvd/pro/b04/sessions/ServerSession.java
  src/main/java/ch/heigvd/pro/b04/sessions/SessionIdentifier.java
  src/main/java/ch/heigvd/pro/b04/sessions/SessionRepository.java
  src/test/java/ch/heigvd/pro/b04/questions/ServerQuestionTest.java
Labels: priority-high, waiting-for-review

#159 Fix the insertion endpoint for questions
  src/main/java/ch/heigvd/pro/b04/polls/ServerPoll.java
  src/main/java/ch/heigvd/pro/b04/questions/ClientQuestion.java
  src/main/java/ch/heigvd/pro/b04/questions/Question.java
  src/main/java/ch/heigvd/pro/b04/questions/QuestionController.java
  src/main/java/ch/heigvd/pro/b04/questions/QuestionVisibility.java
  src/main/java/ch/heigvd/pro/b04/questions/ServerQuestion.java
  src/main/java/ch/heigvd/pro/b04/questions/ServerQuestionJsonSerializer.java
  src/test/java/ch/heigvd/pro/b04/questions/ServerQuestionTest.java
Labels: priority-high, waiting-for-review

#176 Fix #173 by supporting participant tokens to access individual polls
  src/main/java/ch/heigvd/pro/b04/polls/PollController.java
  src/test/java/ch/heigvd/pro/b04/polls/ServerPollControllerTest.java
Labels: waiting-for-review

#183 Add presentation feedback notes
  wiki/Presentation.Feedback.md
Labels: documentation, priority-low

#184 Add some meeting notes for 2020-04-27
  wiki/Journal/Journal.md
Labels: priority-low
