Repository heig-PRO-b04/java-backend, pull requests merged in 2020-05, with the labels that each got.

#188 Votes and answers functional
  src/main/java/ch/heigvd/pro/b04/answers/ServerAnswer.java
  src/main/java/ch/heigvd/pro/b04/participants/Participant.java
  src/main/java/ch/heigvd/pro/b04/questions/ClientQuestion.java
  src/main/java/ch/heigvd/pro/b04/questions/QuestionController.java
  src/main/java/ch/heigvd/pro/b04/questions/ServerQuestion.java
  src/main/java/ch/heigvd/pro/b04/questions/ServerQuestionJsonSerializer.java
  src/main/java/ch/heigvd/pro/b04/votes/ClientVote.java
  src/main/java/ch/heigvd/pro/b04/votes/ServerVote.java
  src/main/java/ch/heigvd/pro/b04/votes/ServerVoteRepository.java
  src/main/java/ch/heigvd/pro/b04/votes/Vote.java
  src/main/java/ch/heigvd/pro/b04/votes/VoteController.java
Labels: waiting-for-review

#191 Add a specification for a poll statistics endpoint
  wiki/APIv1.Endpoints.md
  wiki/APIv1.Objects.md
Labels: waiting-for-review

#192 Fix question visibility for participants
  src/main/java/ch/heigvd/pro/b04/questions/QuestionController.java
Labels: bug, waiting-for-review

#193 Fix TOC
  wiki/APIv1.Endpoints.md
  wiki/APIv1.Objects.md
Labels: api, documentation

#197 Add a checked field to answers
  src/main/java/ch/heigvd/pro/b04/answers/AnswerController.java
  src/main/java/ch/heigvd/pro/b04/answers/ServerAnswer.java
  wiki/APIv1.Objects.md
Labels: waiting-for-review

#198 Persist data when the backend upgrades
  src/main/resources/application.properties
Labels: waiting-for-review

#199 Add question-specific statistics
  src/main/java/ch/heigvd/pro/b04/answers/AnswerRepository.java
  src/main/java/ch/heigvd/pro/b04/statistics/ServerQuestionStatistics.java
  src/main/java/ch/heigvd/pro/b04/statistics/StatisticsController.java
  src/main/java/ch/heigvd/pro/b04/votes/ServerVoteRepository.java
  wiki/APIv1.Objects.md
Labels: waiting-for-review

#200 Use Post rather than Get HTTP verb
  src/main/java/ch/heigvd/pro/b04/statistics/StatisticsController.java
  wiki/APIv1.Endpoints.md
Labels: priority-high, waiting-for-review

#206 Add some account management endpoints
  integration-tests/api.py
  src/main/java/ch/heigvd/pro/b04/account/AccountController.java
  src/main/java/ch/heigvd/pro/b04/account/CurrentPassword.java
  src/main/java/ch/heigvd/pro/b04/account/NewPassword.java
  src/main/java/ch/heigvd/pro/b04/account/NewUsername.java
  src/main/java/ch/heigvd/pro/b04/auth/TokenUtils.java
Labels: api, priority-high, waiting-for-review

#215 Add wiki pages for android frontend
  wiki/Android.Code.md
  wiki/Android.Home.md
  wiki/Android.Install.md
Labels: documentation, priority-medium

#218 Fix api.py
  integration-tests/api.py
Labels: bug

#217 Add first iteration of the 'Suivi Qualité' for the final report
  wiki/SuiviQualité.md
Labels: waiting-for-review

#222 Add content to the report
  wiki/Home.md
  wiki/Rapport.md
  wiki/ReportTOC.md
  wiki/SuiviQualité.md
Labels: documentation, wip

#229 Fix disconnection when not OPEN bug
  integration-tests/testSessionStatus.py
  src/main/java/ch/heigvd/pro/b04/polls/PollController.java
Labels: bug

#230 Hotfix
  integration-tests/api.py
  integration-tests/testSessionStatus.py
  integration-tests/testVotes.py
  src/main/java/ch/heigvd/pro/b04/votes/VoteController.java
  src/test/java/ch/heigvd/pro/b04/votes/VoteControllerTest.java
Labels: bug
